### ISSUE TITLE
name 'SANE_LIB' is not defined

### ISSUE THREAD

**Issue by xinyu3ru** [jflesch/pyinsane#18]
F:\pyinsane>python
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:15:05) [MSC v.1600 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyinsane.abstract as pyinsane
C:\Python34\lib\importlib\_bootstrap.py:1161: UserWarning: Module pyinsane was a
lready imported from C:\Python34\lib\site-packages\pyinsane-1.3.8_git-py3.4.egg\
pyinsane\__init__.py, but f:\pyinsane is being added to sys.path
  spec.loader.load_module(spec.name)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\pyinsane-1.3.8_git-py3.4.egg\pyinsane\abst
ract.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\pyinsane-1.3.8_git-py3.4.egg\pyinsane\rawa
pi.py", line 440, in <module>
NameError: name 'SANE_LIB' is not defined

hi, I don't know why 'name 'SANE_LIB' is not defined'
did I miss something?

**Comment by jflesch** [comment]
1) You need to know that Pyinsane doesn't support Windows.

2) Even if it would, Sane on Windows only support network scanners (--> they must be hosted by a Linux machine if I'm not mistaken).

3) There is actually a bug in Pyinsane:

```
try:
    SANE_LIB = ctypes.cdll.LoadLibrary("libsane.so.1")
    sane_available = True
except OSError:
    sane_available = False
(...)
SANE_LIB.sane_init.argtypes = [ctypes.POINTER(ctypes.c_int), AUTH_CALLBACK_DEF]
SANE_LIB.sane_init.restype = ctypes.c_int
```

^ Pyinsane should actually load. It's just that the function is_sane_available() should return False.
I'll fix that asap.

**Comment by jflesch** [comment]
ebb4933f3222872c669441155e7003a025405602

**Comment by xinyu3ru** [comment]
Thanks and feel sorry about made a trouble。
