### ISSUE TITLE
I can't use the color mode with my brother

### ISSUE THREAD

**Issue by rrmelcer** [jflesch/pyinsane#22]
With the device [Brother MVC-J410](http://support.brother.com/g/b/producttop.aspx?c=as_ot&lang=en&prod=mfcj410_all) the follow line of code produce the follow error masage.
```python
device.options['mode'].value = 'Color'
```
```error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyinsane/abstract.py", line 95, in _set_value
    rawapi.sane_set_option_value(sane_dev_handle[1], self.idx, new_value)
  File "/usr/local/lib/python2.7/dist-packages/pyinsane/rawapi.py", line 632, in sane_set_option_value
    raise SaneException(SaneStatus(status))
pyinsane.rawapi.SaneException: <class 'pyinsane.rawapi.SaneStatus'> : Data is invalid (4)
```

**Comment by jflesch** [comment]
Can you run the script 'examples/list_all.py' and post the output here please ?

**Comment by rrmelcer** [comment]
Python 2.7 under Linux Mint 7.1
```
Scanner 'brother3:bus3;dev1' (Brother, MFC-J410, USB scanner)
  Option: brightness
    Title: Brightness
    Desc: Controls the brightness of the acquired image.
    Type: <class 'pyinsane.rawapi.SaneValueType'> : Fixed (2)
    Unit: <class 'pyinsane.rawapi.SaneUnit'> : Percent (5)
    Size: 4
    Capabilities: <class 'pyinsane.rawapi.SaneCapabilities'> :[ Inactive, Soft_select, Soft_detect,]
    Constraint type: <class 'pyinsane.rawapi.SaneConstraintType'> : Range (1)
    Constraint: (-3276800, 3276800, 65536)
    Value: Failed to get the value: Option 'brightness' is not active
  Option: tl-y
    Title: Top-left y
    Desc: Top-left y position of scan area.
    Type: <class 'pyinsane.rawapi.SaneValueType'> : Fixed (2)
    Unit: <class 'pyinsane.rawapi.SaneUnit'> : Mm (3)
    Size: 4
    Capabilities: <class 'pyinsane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
    Constraint type: <class 'pyinsane.rawapi.SaneConstraintType'> : Range (1)
    Constraint: (0, 23304601, 6553)
    Value: 0
  Option: tl-x
    Title: Top-left x
    Desc: Top-left x position of scan area.
    Type: <class 'pyinsane.rawapi.SaneValueType'> : Fixed (2)
    Unit: <class 'pyinsane.rawapi.SaneUnit'> : Mm (3)
    Size: 4
    Capabilities: <class 'pyinsane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
    Constraint type: <class 'pyinsane.rawapi.SaneConstraintType'> : Range (1)
    Constraint: (0, 14149222, 6553)
    Value: 0
  Option: br-y
    Title: Bottom-right y
    Desc: Bottom-right y position of scan area.
    Type: <class 'pyinsane.rawapi.SaneValueType'> : Fixed (2)
    Unit: <class 'pyinsane.rawapi.SaneUnit'> : Mm (3)
    Size: 4
    Capabilities: <class 'pyinsane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
    Constraint type: <class 'pyinsane.rawapi.SaneConstraintType'> : Range (1)
    Constraint: (0, 23304601, 6553)
    Value: 23304601
  Option: br-x
    Title: Bottom-right x
    Desc: Bottom-right x position of scan area.
    Type: <class 'pyinsane.rawapi.SaneValueType'> : Fixed (2)
    Unit: <class 'pyinsane.rawapi.SaneUnit'> : Mm (3)
    Size: 4
    Capabilities: <class 'pyinsane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
    Constraint type: <class 'pyinsane.rawapi.SaneConstraintType'> : Range (1)
    Constraint: (0, 14149222, 6553)
    Value: 14149222
  Option: source
    Title: Scan source
    Desc: Selects the scan source (such as a document-feeder).
    Type: <class 'pyinsane.rawapi.SaneValueType'> : String (3)
    Unit: <class 'pyinsane.rawapi.SaneUnit'> : None (0)
    Size: 64
    Capabilities: <class 'pyinsane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
    Constraint type: <class 'pyinsane.rawapi.SaneConstraintType'> : String list (3)
    Constraint: ['FlatBed', 'Automatic Document Feeder(left aligned)', 'Automatic Document Feeder(centrally aligned)']
    Value: Automatic Document Feeder(left aligned)
  Option: mode
    Title: Scan mode
    Desc: Select the scan mode
    Type: <class 'pyinsane.rawapi.SaneValueType'> : String (3)
    Unit: <class 'pyinsane.rawapi.SaneUnit'> : None (0)
    Size: 30
    Capabilities: <class 'pyinsane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
    Constraint type: <class 'pyinsane.rawapi.SaneConstraintType'> : String list (3)
    Constraint: ['Black & White', 'Gray[Error Diffusion]', 'True Gray', '24bit Color']
    Value: 24bit Color
  Option: resolution
    Title: Scan resolution
    Desc: Sets the resolution of the scanned image.
    Type: <class 'pyinsane.rawapi.SaneValueType'> : Integer (1)
    Unit: <class 'pyinsane.rawapi.SaneUnit'> : Dpi (4)
    Size: 4
    Capabilities: <class 'pyinsane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
    Constraint type: <class 'pyinsane.rawapi.SaneConstraintType'> : Word list (2)
    Constraint: [100, 150, 200, 300, 400, 600, 1200, 2400, 4800, 9600]
    Value: 200
  Option: contrast
    Title: Contrast
    Desc: Controls the contrast of the acquired image.
    Type: <class 'pyinsane.rawapi.SaneValueType'> : Fixed (2)
    Unit: <class 'pyinsane.rawapi.SaneUnit'> : Percent (5)
    Size: 4
    Capabilities: <class 'pyinsane.rawapi.SaneCapabilities'> :[ Inactive, Soft_select, Soft_detect,]
    Constraint type: <class 'pyinsane.rawapi.SaneConstraintType'> : Range (1)
    Constraint: (-3276800, 3276800, 65536)
    Value: Failed to get the value: Option 'contrast' is not active

```

**Comment by jflesch** [comment]
```
Option: mode
(...)
Constraint: ['Black & White', 'Gray[Error Diffusion]', 'True Gray', '24bit Color']
```

#%#$^#$ !! Because there is always an idiot somewhere to think they are smarter than the others and do things differently for no actual reason ! (not you of course, the guy who made your scanner driver)

**Comment by jflesch** [comment]
So, what you need to do is actually:

```
device.options['mode'].value = '24bit Color'
```

and I, I will have to add another workaround in Paperwork ....

**Comment by rrmelcer** [comment]
Thank you very much for your fast support.

**Comment by jflesch** [comment]
I think it should solve your problem, so I'm going to close this ticket. Thank you for taking the time to report this issue.

If you still have a problem with the 'mode' option of your scanner, please fell free to reopen it.

**Comment by rrmelcer** [comment]
OK, I do - your support is great! :+1:
