### ISSUE TITLE
Mac OS X error pyinsane.get_devices()

### ISSUE THREAD

**Issue by lamtritin90** [jflesch/pyinsane#25]
Hi, 
I installed this library and testing it on my OS X.

Everything is ok for the installation.
When i try to make a demo code. 
>>> import pyinsane.abstract as pyinsane
>>> devices = pyinsane.get_devices()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.11-x86_64/egg/pyinsane/abstract.py", line 473, in get_devices
  File "build/bdist.macosx-10.11-x86_64/egg/pyinsane/rawapi.py", line 522, in sane_init
AssertionError

Can you have a look on this one?

**Comment by lamtritin90** [comment]
Sorry I forgot to install libsane, it is ok now!
